version: "4.0"

networks:
  cluster_net:
    external: true

volumes:
  redis-data:

services:

  # ---------------------------------------------------------
  # Frontend / API (runs on ARM Pi workers)
  # ---------------------------------------------------------
  hello-app:
    image: traefik/whoami:v1.10.2
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role == worker
          - node.labels.arch == arm64
    networks:
      - cluster_net
    ports:
      - target: 80
        published: 8080
        mode: ingress
    environment:
      WHOAMI_NAME: "{{.Task.Name}}"
      WHOAMI_HOSTNAME: "{{.Node.Hostname}}"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 10s
      timeout: 2s
      retries: 3

  # ---------------------------------------------------------
  # Redis message bus (runs on manager = i5)
  # ---------------------------------------------------------
  redis-bus:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
          - node.labels.arch == amd64
    volumes:
      - redis-data:/data
    networks:
      - cluster_net

  # ---------------------------------------------------------
  # Lightweight load testers (run on Pi workers)
  # ---------------------------------------------------------
  echo-worker:
    image: curlimages/curl:8.8.0
    command: >
      sh -c '
        while true; do
          echo "--- $(date) ---";
          curl -sw "status=%{http_code} host=%{remote_ip}\n" hello-app:80 || true;
          sleep 5;
        done
      '
    deploy:
      replicas: 2
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == worker
          - node.labels.arch == arm64
    networks:
      - cluster_net

  # ---------------------------------------------------------
  # LLM Texture Upscaler – CPU service (runs ONLY on i5)
  # ---------------------------------------------------------
  llm-upscaler:
    image: yourregistry/texture-upscaler:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "3.5"
          memory: 6G
        reservations:
          cpus: "1.5"
          memory: 2G
      placement:
        constraints:
          - node.labels.arch == amd64
          - node.role == worker  # if i5 is both worker+manager, remove this line
    environment:
      MODEL: "upscale-texture-v1"
      REDIS_HOST: redis-bus
    networks:
      - cluster_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 3s
      retries: 5

  # ---------------------------------------------------------
  # Swarm Dashboard (runs on manager)
  # ---------------------------------------------------------
  swarm-dashboard:
    image: swg-dashboard:local
    networks:
      - cluster_net
    environment:
      OVERLAY_NETWORK: cluster_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - target: 8081
        published: 8081
        mode: ingress
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
          - node.labels.arch == amd64
