version: "4.0"

networks:
  cluster_net:
    external: true

volumes:
  redis-data:

services:

  # ---------------------------------------------------------
  # GPU TEXTURE UPSCALER (runs only on GPU nodes)
  # ---------------------------------------------------------
  llm-upscaler-gpu:
    image: yourregistry/texture-upscaler-gpu:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.gpu == true    # GPU nodes only
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]    # Request GPU
    environment:
      MODEL: "upscale-texture-v1-gpu"
      REDIS_HOST: redis-bus
    networks:
      - cluster_net
    ports:
      - target: 8000
        published: 8000
        mode: ingress
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 12s
      timeout: 3s
      retries: 5

  # ---------------------------------------------------------
  # CPU FALLBACK UPSCALER (runs only on CPU nodes)
  # ---------------------------------------------------------
  llm-upscaler-cpu:
    image: yourregistry/texture-upscaler-cpu:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.cpu == true    # CPU-only nodes
      restart_policy:
        condition: any
    environment:
      MODEL: "upscale-texture-v1"
      REDIS_HOST: redis-bus
    networks:
      - cluster_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/health"]
      interval: 12s
      timeout: 3s
      retries: 5

  # ---------------------------------------------------------
  # REDIS MESSAGE BUS (runs on CPU nodes, saves GPU cycles)
  # ---------------------------------------------------------
  redis-bus:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.cpu == true      # CPU-only
    volumes:
      - redis-data:/data
    networks:
      - cluster_net

  # ---------------------------------------------------------
  # FRONTEND / API (CPU nodes only)
  # ---------------------------------------------------------
  hello-app:
    image: traefik/whoami:v1.10.2
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.cpu == true     # run only on CPU nodes
    networks:
      - cluster_net
    ports:
      - target: 80
        published: 8080
    environment:
      WHOAMI_NAME: "{{.Task.Name}}"
      WHOAMI_HOSTNAME: "{{.Node.Hostname}}"

  # ---------------------------------------------------------
  # LIGHTWORKERS (load testers / job dispatchers)
  # CPU NODES ONLY
  # ---------------------------------------------------------
  echo-worker:
    image: curlimages/curl:8.8.0
    command: >
      sh -c '
        while true; do
          echo "--- $(date) ---";
          curl -sw "status=%{http_code}\n" hello-app:80 || true;
          sleep 5;
        done
      '
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.cpu == true
    networks:
      - cluster_net

  # ---------------------------------------------------------
  # DASHBOARD (CPU nodes only)
  # ---------------------------------------------------------
  swarm-dashboard:
    image: swg-dashboard:local
    networks:
      - cluster_net
    environment:
      OVERLAY_NETWORK: cluster_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - target: 8081
        published: 8081
    deploy:
      placement:
        constraints:
          - node.labels.cpu == true
      restart_policy:
        condition: any
